### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by noterei** [noterei/ereislittlehelper#1]
- [ ] add +urban
- [ ] finish +set, +evals, +set, +poll
- [ ] reformat +todo or just get rid of it
- [ ] twitter, reddit, librefm* streaming
- [ ] various sub events
- [ ] custom tags and all the interface commands for them
- [ ] website

\* check if librefm doesn't completely suck first
